swagger: "2.0"
info:
  title: Bank Argent API documentation (phase 2)
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/{userId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transactions API
      description: API for fetching transactions of the month
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          type: string
          description: Attach user ID to URL
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Successfully fetched transactions
          schema:
            $ref: "#/definitions/TransactionAllResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{userId}/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Create Transaction API
      description: API for creating a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          type: string
          description: Attach user ID to URL
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction successfully created
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{userId}/transaction/{transactionId}:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction API
      description: API for updating a specific transaction details
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          type: string
          description: Attach user ID to URL
          required: true
        - in: path
          name: transactionId
          type: string
          description: Attach transaction ID to URL
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details updated successfully
          schema:
            $ref: "#/definitions/TransactionUpdateResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete transaction API
      description: API for deleting a specific transaction details
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          type: string
          description: Attach user ID to URL
          required: true
        - in: path
          name: transactionId
          type: string
          description: Attach transaction ID to URL
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details deleted successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    properties:
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: user notes
  TransactionAllResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: unique id
            date:
              type: string
              description: transaction date
            description:
              type: string
              description: transaction description
            amount:
              type: number
              description: transaction amount
            balance:
              type: number
              description: balance amount
            type:
              type: string
              description: Transaction's type
            category:
              type: string
              description: Transaction's category
            notes:
              type: string
              description: Transaction's notes
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          type:
            type: string
          category:
            type: string
          notes:
            type: string
  TransactionUpdateResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: unique id
            date:
              type: string
              description: transaction date
            description:
              type: string
              description: transaction description
            amount:
              type: number
              description: transaction amount
            balance:
              type: number
              description: balance amount
            type:
              type: string
              description: Transaction's type
            category:
              type: string
              description: Transaction's category
            notes:
              type: string
              description: Transaction's notes
